### ISSUE TITLE
Add guide to caddyserver/examples

### ISSUE THREAD

**Issue by mholt** [minio/howto#6]
Great idea with this repo :+1:

Would someone be willing to contribute [this Caddy guide](https://github.com/minio/howto/blob/master/setup-Caddy-proxy-with-Minio-Server.md) to [caddyserver/examples](https://github.com/caddyserver/examples)?

All it would take is the Caddyfile and an explanation of what it does, and why it works. Thanks!

**Comment by harshavardhana** [comment]
Sure @mholt we will do so. Thanks for the suggestion.

**Comment by harshavardhana** [comment]
Closing the issue, merged upstream https://github.com/caddyserver/examples/tree/master/minio
