### ISSUE TITLE
Docs for webhook endpoint shows trailing underscore

### ISSUE THREAD

**Issue by bluepuma77** [minio/howto#744]
Docs [Add the Webhook Endpoint to MinIO](https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-webhook.html#minio-bucket-notifications-publish-webhook) show trailing underscores:

```
set MINIO_NOTIFY_WEBHOOK_ENABLE_<IDENTIFIER>_="on"
set MINIO_NOTIFY_WEBHOOK_ENDPOINT_<IDENTIFIER>_="ENDPOINT"
set MINIO_NOTIFY_WEBHOOK_AUTH_TOKEN_<IDENTIFIER>_="<string>"
set MINIO_NOTIFY_WEBHOOK_QUEUE_DIR_<IDENTIFIER>_="<string>"
set MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT_<IDENTIFIER>_="<string>"
set MINIO_NOTIFY_WEBHOOK_CLIENT_CERT_<IDENTIFIER>_="<string>"
set MINIO_NOTIFY_WEBHOOK_CLIENT_KEY_<IDENTIFIER>_="<string>"
set MINIO_NOTIFY_WEBHOOK_COMMENT_<IDENTIFIER>_="<string>"
                                             ^
```

I think that is misleading, the [Webhook Service for Bucket Notifications](https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio-server-envvar-bucket-notification-webhook) shows that no trailing underscore is used:
```
set MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY="on"
```

**Comment by ravindk89** [comment]
I can guess where that typo came from. Small fix. Thanks for identifying it
